---@type KanaRule[]
local Rules = {
  { input = "b", output = "ㄅ", next = "" },
  { input = "p", output = "ㄆ", next = "" },
  { input = "m", output = "ㄇ", next = "" },
  { input = "f", output = "ㄈ", next = "" },
  { input = "d", output = "ㄉ", next = "" },
  { input = "t", output = "ㄊ", next = "" },
  { input = "n", output = "ㄋ", next = "" },
  { input = "l", output = "ㄌ", next = "" },
  { input = "g", output = "ㄍ", next = "" },
  { input = "k", output = "ㄎ", next = "" },
  { input = "h", output = "ㄏ", next = "" },
  { input = "j", output = "ㄐ", next = "" },
  { input = "q", output = "ㄑ", next = "" },
  { input = "x", output = "ㄒ", next = "" },
  { input = "zh", output = "ㄓ", next = "" },
  { input = "ch", output = "ㄔ", next = "" },
  { input = "sh", output = "ㄕ", next = "" },
  { input = "r", output = "ㄖ", next = "" },
  { input = "z", output = "ㄗ", next = "" },
  { input = "c", output = "ㄘ", next = "" },
  { input = "s", output = "ㄙ", next = "" },
  { input = "a", output = "ㄚ", next = "" },
  { input = "e", output = "ㄜ", next = "" },
  { input = "ai", output = "ㄞ", next = "" },
  { input = "ao", output = "ㄠ", next = "" },
  { input = "ou", output = "ㄡ", next = "" },
  { input = "an", output = "ㄢ", next = "" },
  { input = "en", output = "ㄣ", next = "" },
  { input = "ang", output = "ㄤ", next = "" },
  { input = "er", output = "ㄦ", next = "" },
  { input = "i", output = "ㄧ", next = "" },
  { input = "u", output = "ㄨ", next = "" },
  { input = "y", output = "ㄩ", next = "" },
}
return Rules
